version: "3"

networks:
  splunknet:
    driver: bridge
    attachable: true

services:
  sbf:
    restart: always
    networks:
      splunknet:
        aliases:
          - sbf
    image: splunk/splunk:latest
    container_name: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=changeme
      - SPLUNK_HEC_TOKEN=00000000-0000-0000-0000-000000000000
      - DEBUG=true
      - SPLUNK_APPS_URL=
    ports:
      - 8000:8000
      - 8088:8088
      - 8089:8089
